# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21b4c0a9d6281f5be2f20872a3eeac36"
application_url = "https://fails-inside-mods-accepted.trycloudflare.com"
embedded = true
name = "Komparo"
handle = "komparo-2"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fails-inside-mods-accepted.trycloudflare.com/auth/callback",
  "https://fails-inside-mods-accepted.trycloudflare.com/auth/shopify/callback",
  "https://fails-inside-mods-accepted.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "pricepredictions.myshopify.com"
automatically_update_urls_on_dev = true
