# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "36c68ffb8e0d642626679a4448405849"
application_url = "https://domains-tsunami-ethical-ko.trycloudflare.com"
embedded = true
name = "price-comparison-app"
handle = "price-comparison-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://domains-tsunami-ethical-ko.trycloudflare.com/auth/callback",
  "https://domains-tsunami-ethical-ko.trycloudflare.com/auth/shopify/callback",
  "https://domains-tsunami-ethical-ko.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "price-comparison-app.myshopify.com"
automatically_update_urls_on_dev = true
