# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14eecd3c23b30159050b0aee0b714c16"
application_url = "https://add-humanities-basketball-population.trycloudflare.com"
embedded = true
name = "price-comparison-app"
handle = "price-comparison-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://add-humanities-basketball-population.trycloudflare.com/auth/callback",
  "https://add-humanities-basketball-population.trycloudflare.com/auth/shopify/callback",
  "https://add-humanities-basketball-population.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "price-comparison-app.myshopify.com"
automatically_update_urls_on_dev = true
