# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "734580de7f1c2eff34c67313dbde400c"
application_url = "https://chapter-academy-americans-correspondence.trycloudflare.com"
embedded = true
name = "PricePredictions"
handle = "PricePredictions"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://chapter-academy-americans-correspondence.trycloudflare.com/auth/callback",
  "https://chapter-academy-americans-correspondence.trycloudflare.com/auth/shopify/callback",
  "https://chapter-academy-americans-correspondence.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "pricepredictions.myshopify.com"
automatically_update_urls_on_dev = true
